intel/ibc: Use the vote source type for the CMP null destination type
For vote_feq, we were generating a UW destination but F sources, which
led to a EU validation failure:

   cmp.z.f1.0(8)   null<1>W  g4<0,1,0>F  g4<0,1,0>F  { align1 1Q };
   ERROR: Destination stride must be equal to the ratio of the sizes of
          the execution data type to the destination type

Just make the destination type match so it's the right size.